/*
 * This source file was generated by the Gradle 'init' task
 */
package bcc.swinggame;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        
        assertNotNull("N/a", "Hi");
    }
}
